### ISSUE TITLE
Un error y un comentario

### ISSUE THREAD

**Issue by manuelbarrosr** [tresquintos/tresquintos.github.io#1]
Hola, Keneth.

Está muy interesante la renovación de proyecto. Soy más fan del logo antiguo, pero se ve que vienen buenos los aportes para el año. Te dejo un error y un comentario:

1. El link al TSM desde la página [Presidenciales 2021](https://tresquintos.cl/presidenciales2021/) está roto, porque está linkeando a http://kenethbunker.cl/tsm y no a https://tresquintos.cl/tsm/

2. Creo que el logo grande, en el menú lateral izquierdo, debería linkear al home. Por una cuestión de UX, todos tendemos a hacer cilc en los logos para volver al home.

Saludos :)

**Comment by kennethbunker** [comment]
Gracias, Manuel. Cualquier otro comentario o sugerencias me lo haces saber. Saludos!

**Comment by kennethbunker** [comment]
Por cierto, sabes como linkear el logo al home?
